### PR TITLE
Moved DTOs,Mappings,Validations from DAL to BLL,fix issues that appeared

### PR DESCRIPTION
**Pull request by VitalikRibiy**

### CODE REVIEW

**Review by Vladacdc — DISMISSED** [review]

**Review by BohdanBuhrii — DISMISSED** [review]

**Review by igolovchuk — CHANGES_REQUESTED** [review]
- I still see references in API project to DAL project, please remove all dependencies on DAL from API, and make changes needed for that,(Or if this is the task of another student please write into a comment)
- in DAL project, '/Models/ViewModels', please move all these files to DTOs and rename appropriately, eg 'LoginVievModel' -> LoginDTO

**Comment by VitalikRibiy** [comment]
@igolovchuk 
Moved ViewModels

What about references in API project,it is task of @BohdanBuhrii

**Comment by Vladacdc** [comment]
@VitalikRibiy There is no need to commit migrations, isn't it?

**Comment by igolovchuk** [comment]
> @VitalikRibiy There is no need to commit migrations, isn't it?

no need migrations enabled at all i think

**Review by igolovchuk — CHANGES_REQUESTED** [review]
remove all migrations for now

**Comment by VitalikRibiy** [comment]
@igolovchuk  Removed migrations.
@Vladacdc add migrations to gitIgnore pls

**Review by igolovchuk — APPROVED** [review]

**Review by Vladacdc — APPROVED** [review]

**Review by BohdanBuhrii — APPROVED** [review]

**Pull request merged**
